name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for helping to bring Muzeplore, the digital museum art-sharing site to life!"
        pr-message: "Thank you for creating a pull request. It will be analyzed shortly."
